version: '3'
services:
  web:
    build: .
    # image: tamura/workplan
    ports:
      - "80:3000"
    volumes:
      - .:/workplan
    environment:
      - DB_USERNAME=tamura
      - DB_PASSWORD=tamura
      - DB_HOST=db
  db:
    image: postgres
    environment:
      - POSTGRES_USER=tamura
      - POSTGRES_PASSWORD=tamura
      - POSTGRES_DB=prod_work